"""phase3 watchlist item token_id fk and drop description

Revision ID: 8013a722e4d1
Revises: 906ff88e1959
Create Date: 2026-06-12 16:43:44.805035

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8013a722e4d1'
down_revision: Union[str, None] = '906ff88e1959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('token_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_watchlist_item_coin'), 'watchlist_items', type_='unique')
    op.create_index(op.f('ix_watchlist_items_token_id'), 'watchlist_items', ['token_id'], unique=False)
    op.create_unique_constraint('uq_watchlist_item_token', 'watchlist_items', ['watchlist_id', 'token_id'])
    op.create_foreign_key(
        'fk_watchlist_items_token_id', 'watchlist_items', 'tokens',
        ['token_id'], ['id'], ondelete='CASCADE',
    )
    op.drop_column('watchlist_items', 'coin_id')
    op.drop_column('watchlist_items', 'updated_at')
    op.drop_column('watchlist_items', 'symbol')
    op.drop_column('watchlists', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('watchlist_items', sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('watchlist_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('watchlist_items', sa.Column('coin_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint('fk_watchlist_items_token_id', 'watchlist_items', type_='foreignkey')
    op.drop_constraint('uq_watchlist_item_token', 'watchlist_items', type_='unique')
    op.drop_index(op.f('ix_watchlist_items_token_id'), table_name='watchlist_items')
    op.create_unique_constraint(op.f('uq_watchlist_item_coin'), 'watchlist_items', ['watchlist_id', 'coin_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('watchlist_items', 'token_id')
    # ### end Alembic commands ###
