"""phase4 alerts token_id fk and is_active

Revision ID: f32296c31929
Revises: 8013a722e4d1
Create Date: 2026-06-12 17:07:48.064004

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32296c31929'
down_revision: Union[str, None] = '8013a722e4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('token_id', sa.Uuid(), nullable=False))
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_alerts_coin_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_alerts_token_id'), 'alerts', ['token_id'], unique=False)
    op.create_foreign_key(
        'fk_alerts_token_id', 'alerts', 'tokens', ['token_id'], ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'coin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('coin_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint('fk_alerts_token_id', 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_token_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.create_index(op.f('ix_alerts_coin_id'), 'alerts', ['coin_id'], unique=False)
    op.drop_column('alerts', 'is_active')
    op.drop_column('alerts', 'token_id')
    # ### end Alembic commands ###
